name: Deploy to Minikube using GitHub Actions

on:
  workflow_dispatch:
    inputs: 
      AppName:
        type: choice
        description: Name of the application
        options: 
        - nginx
        - httpd
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: deploy minikube
    steps:
    - uses: actions/checkout@v4

    - name: Start minikube
      uses: medyagh/setup-minikube@latest

    - name: Checking cluster
      run: |
        kubectl get pods -A
        kubectl create namespace nginx
        kubectl create namespace apache

    - name: Install Helm 
      uses: azure/setup-helm@v4.2.0
      id: install

    - name: Run the installation script
      shell: pwsh
      run: |
        .\scripts\InstallationScript.ps1 -app "$APP" -path '.'
      env:
        APP: ${{ github.event.inputs.AppName }}

    - name: Checking cluster
      run: kubectl get pods -A
