name: Deploy to Minikube using GitHub Actions

on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: deploy minikube
    steps:
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Try the cluster!
      run: kubectl get pods -A