name: Deploy to Minikube using GitHub Actions

on:
  workflow_dispatch:
    inputs: 
      appname:
        type: choice
        description: Name of the application
        options: 
        - nginx
        - httpd
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: deploy minikube
    steps:
    - uses: actions/checkout@v4

    - name: Start minikube
      uses: medyagh/setup-minikube@latest

    - name: Checking cluster / Creation of namespaces
      run: |
        kubectl get pods -A
        kubectl create namespace nginx
        kubectl create namespace apache

    - name: Install Helm 
      uses: azure/setup-helm@v4.2.0
      id: install

    - name: Cilium installation
      shell: pwsh
      run: |
        helm repo add cilium https://helm.cilium.io/
        helm install -n kube-system cilium cilium/cilium -f cilium/cilium-values.yaml
        sleep 20
        kubectl get daemonsets -n kube-system
        kubectl get po -A
        kubectl get configmaps -n kube-system kubeadm-config -o yaml
        kubectl -n kube-system exec ds/cilium -- cilium-dbg status
        kubectl get ingress -A
        kubectl get service -A

    - name: Cilium LB config
      shell: pwsh
      run: |
        kubectl apply -f cilium/pool.yaml
        kubectl -n kube-system rollout restart deployment/cilium-operator
        kubectl -n kube-system rollout restart ds/cilium
        sleep 10
        kubectl get service -A

    - name: Run the web app installation script
      shell: pwsh
      run: |
        .\scripts\InstallationScript.ps1 -app ${{ github.event.inputs.appname }} -path '.'

    - name: Checking cluster
      run: | 
        sleep 10
        kubectl get pods -A
        kubectl get deployment -A
        kubectl get service -A -o json | ConvertFrom-Json
        ((kubectl get service -A -o json | ConvertFrom-Json).items | where {$_.metadata.name -eq 'nginx'}).status
        ((kubectl get service -A -o json | ConvertFrom-Json).items | where {$_.metadata.name -eq 'nginx'}).spec

