name: Deploy to Minikube using GitHub Actions

on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: deploy minikube
    steps:
    - uses: actions/checkout@v4

    - name: Start minikube
      uses: medyagh/setup-minikube@latest

    - name: Checking cluster
      run: kubectl get pods -A

    - name: Install Helm 
      uses: azure/setup-helm@v4.2.0
      id: install

    - name: Run the installation script
      shell: pwsh
      run: |
        .\scripts\InstallationScript.ps1 -app httpd -path '.'

    - name: Checking cluster
      run: kubectl get pods -A
