name: Deploy to Minikube using GitHub Actions

on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: deploy minikube
    steps:
    - uses: actions/checkout@v4

    # - name: Start minikube
    #   uses: medyagh/setup-minikube@latest

    # - name: Checking cluster
    #   run: kubectl get pods -A

    - name: Install Helm 
      uses: azure/setup-helm@v4.2.0
      with:
         version: default
      id: install

    - name: Run the installation script
      shell: pwsh
      working-directory: configuration
      run: |
        ls
        helm version
